homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mosquitto'
  user: mosquitto
  # Enter mosquitto password here
  password: ''
serial:
  port: /dev/ttyACM0
  disable_led: true
advanced:
  # Optional: network encryption key, will improve security (Note: changing requires repairing of all devices)
  network_key: [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13]
  last_seen: epoch
devices: []
